### ISSUE TITLE
ValueError: unknown url type: ''

### ISSUE THREAD

**Issue by bfheythem** [the-robot/animeheaven-downloader#3]
things were going just fine , I manged to download 4 episodes than i received this error I have know idea what  caused the problem 
![screenshot from 2017-12-29 22-37-05](https://user-images.githubusercontent.com/22716581/34447927-02ee7930-ece9-11e7-9703-bd9013283cd8.png)

**Comment by bfheythem** [comment]
Yeah ,obviously that's the problem 
animeHeaven Blocks you from accessing to video when you reach 4 Episodes 
another problem I faced , it didnt work on Windows in the first place so I tried to launch it on linux (and it worked ) any ideas why ?

and thanks a lot for your amazing work and help :)

**Comment by bfheythem** [comment]
![image](https://user-images.githubusercontent.com/22716581/37960348-5bb56052-31ad-11e8-867b-201dd0ec15d5.png)
It's stuck in "Getting urls , whats the pbm ?

**Comment by hq-jiang** [comment]
Hi @the-robot, I really appreciate your work. I have encountered the same problem and the issue is the abuse protection triggered by fetching the urls in high frequency, but I have tested a workaround on a fork. Would you mind if I created a pull request?
