### ISSUE TITLE
downloader Stuck in Getting url

### ISSUE THREAD

**Issue by bfheythem** [the-robot/animeheaven-downloader#5]
I think there is a problem with the script , can you please check it 
It might have a been a change within animeheaven links 

I receive this : 
![image](https://user-images.githubusercontent.com/22716581/38190632-057847f4-365d-11e8-9020-a487a5d06836.png)

**Comment by Qoyyuum** [comment]
Most likely because of the Selenium driver couldn't get the episodes properly.
